version: '3.8'

services:
  cap-generator:
    build:
      context: ./cap-generator
      dockerfile: Dockerfile
    volumes:
      - ./cap-generator:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - emma-net

  ns3-sim:
    build:
      context: ./ns3-sim
      dockerfile: Dockerfile
    privileged: true  # Required for network simulation
    networks:
      - emma-net
    depends_on:
      - cap-generator

  http-cdn:
    build:
      context: ./http-cdn
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./http-cdn/alerts:/app/alerts
    networks:
      - emma-net
    depends_on:
      - cap-generator

  ue-emulator:
    build:
      context: ./ue-emulator
      dockerfile: Dockerfile
    privileged: true  # Required for Android emulator
    network_mode: host  # Required for multicast
    depends_on:
      - ns3-sim
      - http-cdn

networks:
  emma-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 